language: php

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: SYMFONY_VERSION="2.4.*" COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: SYMFONY_VERSION="2.4.*" COMPOSER_FLAGS="--prefer-lowest"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
