language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

before_install:
  - composer self-update

install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
