language: php

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/phan-ast/build

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

before_install:
  - composer self-update
  - .phan/travis_setup.sh

install:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer install --dev --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phan

